apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${appName}
  name: ${appName}
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${appName}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${appName}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-config: 'crds/data/psql'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "crds/data/psql" -}}
            export DB_USERNAME="{{ .Data.data.username }}"
            export DB_PASSWORD="{{ .Data.data.password }}"
          {{- end }}
        vault.hashicorp.com/role: 'todos'
    spec:
      serviceAccountName: todos
      containers:
      - image: omerurhan/todos:${commitId}
        name: ${appName}
        command: ['sh', '-c']
        args: ['source /vault/secrets/config && /app/todos']
        env:
        - name: DB_ADDRESS
          value: "postgresql.database"
        - name: DB_NAME
          value: "todos"
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
status: {}
