apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${appName}
  name: ${appName}
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${appName}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${appName}
    spec:
      containers:
      - image: omerurhan/todods:${commitId}
        name: ${appName}
        env:
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_ADDRESS
          value: "postgresql.database"
        - name: DB_NAME
          value: "todos"
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
status: {}
